Change the install to only work inside the cloned repo tree

diff --git a/install/install b/install/install
--- a/install/install
+++ b/install/install
@@ -25,7 +25,7 @@ __status__="Development"
 THIS_DIR=$(cd $(dirname $0); pwd)
 THIS_FILE=$(basename $0)
 SRC_DIR=$THIS_DIR"/sources"
-ROOT_DIR=$(cd $THIS_DIR/..; pwd)
+# ROOT_DIR=$(cd $THIS_DIR/..; pwd)
 PREFIX=`echo $THIS_DIR | sed -e "s%/install%%"`
 RAPD_VERSION=$(grep RAPD_VERSION $THIS_DIR/../src/version.py | cut -d'"' -f2)
 
@@ -40,7 +40,7 @@ INSTALL_PYTHON=1
 PLATFORM=$(uname -s)
 
 # Handle command line
-while getopts "bcfhimop:sty" x; do
+while getopts "bcfhimosty" x; do
     case "$x" in
         h)
             echo "usage: $0 [options]
@@ -53,7 +53,6 @@ Installs RAPD v$RAPD_VERSION
     -h           print this help message and exit
     -m           skip installed modules query
     -o           overwrite cctbx
-    -p PREFIX    install prefix, defaults to $PREFIX
 
     Install or reinstall
     -t           cctbx
@@ -73,9 +72,6 @@ Installs RAPD v$RAPD_VERSION
         f)
             FORCE=1
             ;;
-        p)
-            PREFIX="$OPTARG"
-            ;;
         o)
             OVERWRITE=1
             ;;
@@ -87,7 +83,6 @@ Installs RAPD v$RAPD_VERSION
             printf "Finished.\n"
             exit 0
             ;;
-
         t)
             INSTALL_CCTBX=1
             INSTALL_INIT=0
@@ -122,13 +117,10 @@ done
 # First test for installed modules
 if [[ $PLATFORM == "Linux" ]]; then
 
-  printf "\033[94mChecking installed packages\033[0m\n"
-
   # Cent OS
   if [ -f /etc/centos-release ]; then
 
-    FLAVOR="CentOS"
-    printf "  $FLAVOR\n"
+    LINUX_FLAVOR="CentOS"
     CENTOS_VERSION_MAJOR=`cat /etc/centos-release | cut -d" " -f4 | cut -d "." -f1`
 
     if [ $CENTOS_VERSION_MAJOR == "6" ]; then
@@ -144,6 +136,7 @@ if [[ $PLATFORM == "Linux" ]]; then
         false
       fi
     }
+    printf "\033[94mChecking installed packages required for $LINUX_FLAVOR $CENTOS_VERSION_MAJOR \033[0m\n"
 
     error=0
     missing_packages=""
@@ -173,8 +166,9 @@ if [[ $PLATFORM == "Linux" ]]; then
 
     if [[ $OS == "ubuntu" ]]; then
 
-      FLAVOR="Ubuntu"
-      printf "  $FLAVOR\n"
+      LINUX_FLAVOR="Ubuntu"
+
+      printf "\033[94mChecking installed packages required for $LINUX_FLAVOR \033[0m\n"
 
       MODULES_LIST="wget subversion git bzip2 libncurses5-dev zlib1g-dev libssl-dev pkg-config python build-essential libgl1-mesa-dev libglu1-mesa-dev"
 
@@ -222,20 +216,20 @@ RAPD2 will be installed into this location:
 $PREFIX
   - Press ENTER to confirm the location
   - Press CTRL-C to abort the installation
-  - Or specify a different location below
 
 [$PREFIX] >>> "
   read user_prefix
   if [[ $user_prefix != "" ]]; then
-      case "$user_prefix" in
-          *\ * )
-              echo "ERROR: Cannot install into directories with spaces" >&2
-              exit 1
-              ;;
-          *)
-              eval PREFIX="$user_prefix"
-              ;;
-      esac
+    exit 9
+#      case "$user_prefix" in
+#          *\ * )
+#              echo "ERROR: Cannot install into directories with spaces" >&2
+#              exit 1
+#              ;;
+#          *)
+#              eval PREFIX="$user_prefix"
+#              ;;
+#      esac
   fi
 fi # ! BATCH
 
@@ -247,19 +241,24 @@ if [[ ($FORCE == 0) && (-e $PREFIX/share) ]]; then
 fi
 
 # Make the target directory
-if [ ! -e $PREFIX ]; then
-  mkdir -p $PREFIX
-  if (( $? )); then
-      echo "ERROR: Could not create directory: $PREFIX" >&2
-      exit 1
-  fi
-fi
-PREFIX=$(cd $PREFIX; pwd)
+# echo $ROOT_DIR
+# echo $PREFIX
+# exit 0
 
-# Install the rapd src tree
-if [[ $ROOT_DIR != $PREFIX ]]; then
-  rsync -a $ROOT_DIR/* $PREFIX/.
-fi
+## Installing into directory not the currently cloned tree?
+#if [ ! -e $PREFIX ]; then
+#  mkdir -p $PREFIX
+#  if (( $? )); then
+#      echo "ERROR: Could not create directory: $PREFIX" >&2
+#      exit 1
+#  fi
+#fi
+#PREFIX=$(cd $PREFIX; pwd)
+
+## Install the rapd src tree
+#if [[ $ROOT_DIR != $PREFIX ]]; then
+#  rsync -a $ROOT_DIR/* $PREFIX/.
+#fi
 
 if [ $INSTALL_CCTBX == 1 ]; then
 
@@ -438,7 +437,7 @@ if [ $INSTALL_PYTHON == 1 ]; then
   rapd.pip install scipy
   # Get the up arrow working in the CLI
   if [[ $PLATFORM == "Linux" ]]; then
-    if [[ $FLAVOR == "CentOS" ]]; then
+    if [[ $LINUX_FLAVOR == "CentOS" ]]; then
       if [[ $CENTOS_VERSION_MAJOR == "7" ]]; then
         if [ ! -e /lib64/libncurses.so ]; then
           if [ "$EUID" -ne 0 ]; then
