Working on install script

diff --git a/install/install_cctbx b/install/install_cctbx
--- a/install/install_cctbx
+++ b/install/install_cctbx
@@ -86,41 +86,41 @@ Installs RAPD v$RAPD_VERSION
 done
 
 # First test for installed modules
-if [[ $PLATFORM == "Linux" ]]; then
-
-  printf "\033[94mChecking installed packages\033[0m\n"
-
-  function isinstalled {
-    if yum list installed "$@" >/dev/null 2>&1; then
-      true
-    else
-      false
-    fi
-  }
-
-  error=0
-  missing_packages=""
-  for package in epel-release blas-devel lapack-devel atlas-sse3-devel atlas-devel openblas-devel libffi-devel ImageMagick-devel
-  do
-    if isinstalled $package; then
-      echo "  $package installed";
-    else
-      echo "  $package not installed";
-      missing_packages="$missing_packages $package"
-      error=1
-    fi
-  done
-  if [ $error == 1 ]; then
-    printf "\033[91mERROR: missing package!\033[0m\n"
-    printf "The following packages need to be installed: $missing_packages \n"
-    if [ $SKIP == 0 ]; then
-      printf "Use the -s option to bypass this\n"
-      exit 1
-    fi
-  fi
-elif [[ $PLATFORM == "Linux" ]]; then
-  printf "\033[94mPerforming installation on Mac OS \033[0m\n"
-fi
+# if [[ $PLATFORM == "Linux" ]]; then
+#
+#   printf "\033[94mChecking installed packages\033[0m\n"
+#
+#   function isinstalled {
+#     if yum list installed "$@" >/dev/null 2>&1; then
+#       true
+#     else
+#       false
+#     fi
+#   }
+#
+#   error=0
+#   missing_packages=""
+#   for package in epel-release blas-devel lapack-devel atlas-sse3-devel atlas-devel openblas-devel libffi-devel ImageMagick-devel
+#   do
+#     if isinstalled $package; then
+#       echo "  $package installed";
+#     else
+#       echo "  $package not installed";
+#       missing_packages="$missing_packages $package"
+#       error=1
+#     fi
+#   done
+#   if [ $error == 1 ]; then
+#     printf "\033[91mERROR: missing package!\033[0m\n"
+#     printf "The following packages need to be installed: $missing_packages \n"
+#     if [ $SKIP == 0 ]; then
+#       printf "Use the -s option to bypass this\n"
+#       exit 1
+#     fi
+#   fi
+# elif [[ $PLATFORM == "Linux" ]]; then
+#   printf "\033[94mPerforming installation on Mac OS \033[0m\n"
+# fi
 
 if [[ $BATCH == 0 ]] # interactive mode
 then
