Cleaning up

diff --git a/install/install_cctbx b/install/install_cctbx
--- a/install/install_cctbx
+++ b/install/install_cctbx
@@ -121,15 +121,44 @@ done
 # First test for installed modules
 if [[ $PLATFORM == "Linux" ]]; then
 
+  printf "\033[94mChecking installed packages\033[0m\n"
+
   # Cent OS
   if [ -f /etc/centos-release ]; then
 
     printf "CentOS\n"
 
-  fi
+    function isinstalled {
+      if yum list installed "$@" >/dev/null 2>&1; then
+        true
+      else
+        false
+      fi
+    }
+
+    error=0
+    missing_packages=""
+    for package in wget subversion git make bzip2 openssl-devel gcc-c++ mesa-libGL-devel mesa-libGLU-devel
+    do
+      if isinstalled $package; then
+        echo "  $package installed";
+      else
+        echo "  $package not installed";
+        missing_packages="$missing_packages $package"
+        error=1
+      fi
+    done
+    if [ $error == 1 ]; then
+      printf "\033[91mERROR: missing package!\033[0m\n"
+      printf "The following packages need to be installed: $missing_packages \n"
+      if [ $SKIP == 0 ]; then
+        printf "Use the -s option to bypass this\n"
+        exit 1
+      fi
+    fi
 
   # Ubuntu
-  if [ -f /etc/lsb-release ]; then
+  elif [ -f /etc/lsb-release ]; then
 
     OS=$(awk '/DISTRIB_ID=/' /etc/*-release | sed 's/DISTRIB_ID=//' | tr '[:upper:]' '[:lower:]')
 
@@ -165,43 +194,12 @@ if [[ $PLATFORM == "Linux" ]]; then
           exit 1
         fi
       fi
-
     fi
-
   fi
 
   exit 0
 
-  printf "\033[94mChecking installed packages\033[0m\n"
 
-  function isinstalled {
-    if yum list installed "$@" >/dev/null 2>&1; then
-      true
-    else
-      false
-    fi
-  }
-
-  error=0
-  missing_packages=""
-  for package in wget subversion git make bzip2 openssl-devel gcc-c++ mesa-libGL-devel mesa-libGLU-devel
-  do
-    if isinstalled $package; then
-      echo "  $package installed";
-    else
-      echo "  $package not installed";
-      missing_packages="$missing_packages $package"
-      error=1
-    fi
-  done
-  if [ $error == 1 ]; then
-    printf "\033[91mERROR: missing package!\033[0m\n"
-    printf "The following packages need to be installed: $missing_packages \n"
-    if [ $SKIP == 0 ]; then
-      printf "Use the -s option to bypass this\n"
-      exit 1
-    fi
-  fi
 elif [[ $PLATFORM == "Darwin" ]]; then
   printf "\033[94mPerforming installation on Mac OS \033[0m\n"
 fi
