Adding h5 to cbf code Add error checking in install remove phenix license

diff --git a/install/install_cctbx b/install/install_cctbx
--- a/install/install_cctbx
+++ b/install/install_cctbx
@@ -183,9 +183,9 @@ fi # ! BATCH
 
 # Check for directory already existing
 if [[ ($FORCE == 0) && (-e $PREFIX/share) ]]; then
-    printf "\033[91mERROR: It appears installation has already been performed in the directory: $PREFIX\n" >&2
-    printf "Use -f option to override\033[0m\n" >&2
-    exit 1
+  printf "\033[91mERROR: It appears installation has already been performed in the directory: $PREFIX\n" >&2
+  printf "Use -f option to override\033[0m\n" >&2
+  exit 1
 fi
 
 # Make the new directory
@@ -207,18 +207,24 @@ if [ $INSTALL_CCTBX == 1 ]; then
   else
     printf "\n\033[94mInstalling cctbx \033[0m\n"
 
-    # CCTBX_PREFIX_SRC=$SRC_DIR"/cctbx"
     CCTBX_PREFIX_TGT=$PREFIX"/share/cctbx"
+    rm -rf $CCTBX_PREFIX_TGT
     mkdir -p $CCTBX_PREFIX_TGT
     cd $CCTBX_PREFIX_TGT
 
     # Get the bootstrap installer
     printf "  Downloading CCTBX bootstrap script"
-    # wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py
+    wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py
 
     # Install CCTBX
     printf "  Installing CCTBX"
-    # python bootstrap.py --builder=cctbx
+    python bootstrap.py --builder=cctbx
+
+    if [ ! $? -eq 0 ]
+    then
+      echo "Could not install cctbx" >&2
+      exit 1
+    fi
   fi
 
   printf "\033[92mCCTBX install complete.\033[0m\n"
@@ -319,13 +325,13 @@ if [ $INSTALL_PYTHON == 1 ]; then
 
   # Remove pip if there
   if [[ $PLATFORM == "Darwin" ]]; then
-    rm $PREFIX/share/cctbx/build/bin/cctbx.pip
-    rm $PREFIX/bin/rapd.pip
-    rm $PREFIX/share/cctbx/base/Python.framework/Versions/2.7/bin/pip
+    rm $PREFIX/share/cctbx/build/bin/cctbx.pip > /dev/null
+    rm $PREFIX/bin/rapd.pip > /dev/null
+    rm $PREFIX/share/cctbx/base/Python.framework/Versions/2.7/bin/pip > /dev/null
   elif [[ $PLATFORM == "Linux" ]]; then
-    rm $PREFIX/share/cctbx/build/bin/cctbx.pip
-    rm $PREFIX/bin/rapd.pip
-    rm $PREFIX/share/cctbx/base/bin/pip
+    rm $PREFIX/share/cctbx/build/bin/cctbx.pip > /dev/null
+    rm $PREFIX/bin/rapd.pip > /dev/null
+    rm $PREFIX/share/cctbx/base/bin/pip > /dev/null
   fi
 
   # Install pip
